version: 2

project_name: mise-en-place

before:
  hooks:
    - go mod tidy

builds:
  - id: mise-en-place
    main: ./cmd/mise-en-place
    binary: mise-en-place
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - id: default
    ids:
      - mise-en-place
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - registry.yaml

checksum:
  name_template: checksums.txt

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
